# TASK 3
car price prediction

In [77]:
# importing libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn import preprocessing
from sklearn.metrics import mean_absolute_error

In [78]:
#read the file
data = pd.read_csv("H:\\oasis_internship\\car\\CarPrice_Assignment.csv")

In [57]:
data.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [79]:
data.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [80]:
data.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [81]:
#checking null values
data.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [82]:
#checking uniqueness of each column
data.nunique()

car_ID              205
symboling             6
CarName             147
fueltype              2
aspiration            2
doornumber            2
carbody               5
drivewheel            3
enginelocation        2
wheelbase            53
carlength            75
carwidth             44
carheight            49
curbweight          171
enginetype            7
cylindernumber        7
enginesize           44
fuelsystem            8
boreratio            38
stroke               37
compressionratio     32
horsepower           59
peakrpm              23
citympg              29
highwaympg           30
price               189
dtype: int64

In [83]:
icol=['fueltype','aspiration','doornumber', 'carbody', 'drivewheel', 'enginelocation','enginetype',
       'cylindernumber','fuelsystem']

In [84]:
#converting to categorical
ca=preprocessing.LabelEncoder()
for i in range(len(icol)):
    data[icol[i]]=ca.fit_transform(data[icol[i]])

In [85]:
data.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,1,0,1,2,2,0,94.5,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,1,0,0,3,1,0,99.8,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,1,0,0,3,0,0,99.4,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0

In [86]:
x=data['price']

In [87]:
col=['car_ID', 'symboling', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg']

In [88]:
y=data[col]

In [89]:
#splitting
X_train, X_test, y_train, y_test = train_test_split(y, x, test_size=0.33, random_state=42)

In [90]:
X_train

,car_ID,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
125,126,3,1,0,1,2,2,0,94.5,168.9,...,2,151,5,3.94,3.11,9.5,143,5500,19,27
42,43,1,1,0,1,3,1,0,96.5,169.1,...,2,110,1,3.15,3.58,9.1,100,5500,25,31
156,157,0,1,0,0,3,1,0,95.7,166.3,...,2,98,1,3.19,3.03,9.0,70,4800,30,37
136,137,3,1,1,1,2,1,0,99.1,186.6,...,2,121,5,3.54,3.07,9.0,160,5500,19,26
140,141,2,1,0,1,2,0,0,93.3,157.3,...,2,108,1,3.62,2.64,8.7,73,4400,26,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,1,1,0,1,2,2,0,99.2,178.5,...,3,181,5,3.43,3.27,9.0,160,5200,19,25
14,15,1,1,0,0,3,2,0,103.5,189.0,...,3,164,5,3.31,3.19,9.0,121,4250,20,25
92,93,1,1,0,0,3,1,0,94.5,165.3,...,2,97,1,3.15,3.29,9.4,69,5200,31,37
179,180,3,1,0,1,2,2,0,102.9,183.5,...,3,171,5,3.27,3.35,9.3,161,5200,19,24
102,103,0,1,0,0,4,1,0,100.4,184.6,...,3,181,5,3.43,3.27,9.0,152,5200,17,22

In [91]:
y_train

125    22018.0
42     10345.0
156     6938.0
136    18150.0
140     7603.0
        ...
106    18399.0
14     24565.0
92      6849.0
179    15998.0
102    14399.0
Name: price, Length: 137, dtype: float64

In [92]:
#model building
model = RandomForestRegressor()

In [93]:
#model training
model.fit( X_train,y_train)

RandomForestRegressor()

In [94]:
#model prediction
pred=model.predict(X_test)

In [95]:
#checking mean absolute error
mean_absolute_error(y_test,pred)

1410.1563676470591